name: Move images into docs/images

on:
workflow_dispatch: # ✅ ensures "Run workflow" button shows up
push: # also auto-runs when new images get pushed to docs/
paths:
- 'docs/*.png'
- 'docs/*.jpg'
- 'docs/*.jpeg'
- 'docs/*.gif'
- 'docs/*.svg'
- 'docs/*.webp'
